import type { Metadata } from 'next';
import './globals.css';
import NavBar from '@/components/navBar/NavBar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className="bg-gray-100">
        <div className="w-full max-w-[768px] mx-auto h-screen bg-main-background">
          <div className="relative h-full px-4 sm:px-6 md:px-8">
            {children}
            <NavBar />
          </div>
        </div>
      </body>
    </html>
  );
}
