import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <div className="max-w-[768px] h-screen mx-auto px-4 sm:px-6 md:px-8 bg-main-background">
          {children}
        </div>
      </body>
    </html>
  );
}
